zamren_management_system/Areas/Security/Models/Privilege.cs
using System.ComponentModel.DataAnnotations;
using zamren_management_system.Areas.Identity.Data;
using zamren_management_system.Areas.Workflow.Models;

namespace zamren_management_system.Areas.Security.Models;

public sealed class Privilege
{
    [Key] public string Id { get; set; } = Guid.NewGuid().ToString();

    [StringLength(255)] public string Name { get; set; }

    [Required] [StringLength(255)] public string Description { get; set; }

    [Required] [StringLength(255)] public string Status { get; set; } = Common.Enums.Status.Active.ToString();

    [Required] public string CreatedByUserId { get; set; }

    public ApplicationUser CreatedBy { get; set; }

    [Required] public DateTimeOffset CreatedDate { get; set; }

    public string? ModifiedByUserId { get; set; }

    public ApplicationUser? ModifiedBy { get; set; }

    public DateTimeOffset? ModifiedDate { get; set; }
    public IEnumerable<RolePrivilege>? RolePrivileges { get; set; }
    // public IEnumerable<ModulePrivilege>? ModulePrivileges { get; set; }
    
    public ICollection<ModulePrivilege> ModulePrivileges { get; set; } = new List<ModulePrivilege>();

    public IEnumerable<WkfProcessStep>? WkfProcessSteps { get; set; }
}

zamren_management_system/Areas/Admin/Controllers/Security/PrivilegeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using zamren_management_system.Areas.Security.Configurations.PrivilegeAuthentication;
using zamren_management_system.Areas.Security.Enums;

namespace zamren_management_system.Areas.Admin.Controllers.Security;

[Authorize(Roles = "ADMIN")]
[Area("Admin")]
public class PrivilegeController : Controller
{
    [HttpGet]
    [HasPrivilege(PrivilegeConstant.SEC_MANAGE_SYSTEM_PRIVILEGES)]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    [HasPrivilege(PrivilegeConstant.SEC_MANAGE_SYSTEM_PRIVILEGES)]
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpGet]
    [HasPrivilege(PrivilegeConstant.SEC_MANAGE_SYSTEM_PRIVILEGES)]
    public IActionResult Edit()
    {
        return View();
    }
    
}

zamren_management_system/Areas/Admin/Views/Privilege/Create.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewBag.Title = "Create New Privilege";
    Layout = "_Layout";
}

<nav style="--bs-breadcrumb-divider: '>'; float: right" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Home</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-area="Admin" asp-controller="Privilege" asp-action="Index">Privileges</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Create</li>
    </ol>
</nav>

<div class="row">
    <div class="col-md-6">
        <h1>Create New Privilege</h1>
        <form id="create-privilege-form" class="mt-3">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="name" name="name" placeholder="e.g SEC_CREATE_RECORD">
                <label for="name">Privilege Name</label>
            </div>
            <div class="form-floating mb-3">
                <textarea class="form-control" maxlength="255" id="description" name="description" rows="3" placeholder="Enter privilege description"></textarea>
                <label for="description">Privilege Description</label>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>

@section Scripts {
    <script src="~/js/security/privilege/create.privilege.js"></script>
}

zamren_management_system/Areas/Admin/Views/Privilege/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewBag.Title = "Edit Privilege";
    Layout = "_Layout";
}

<nav style="--bs-breadcrumb-divider: '>'; float: right" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Home</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-area="Admin" asp-controller="Privilege" asp-action="Index">Privileges</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
</nav>

<h1>EDIT PRIVILEGE</h1>
<hr>

<div class="row">
    <div class="col-md-6">
        <form id="edit-privilege-form" class="mt-3">
            <div class="form-group">
                <label for="name">Privilege Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter privilege name">
            </div>
            <br>
            <div class="form-group">
                <label for="description">Privilege Description</label>
                <textarea class="form-control" maxlength="255" id="description" name="description" rows="3" placeholder="Enter privilege description"></textarea>
            </div>
            <br>
            <input type="hidden" id="id" name="id"/>
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </form>
    </div>
</div>


<br>
<br>

@section Scripts {
    <script src="~/js/security/privilege/get.privilege.details.js"></script>
    <script src="~/js/security/privilege/edit.privilege.js"></script>
}

zamren_management_system/Areas/Admin/Views/Privilege/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewBag.Title = "Privileges";
    Layout = "_Layout";
}


<nav style="--bs-breadcrumb-divider: '>'; float: right" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Home</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Privileges</li>
    </ol>
</nav>

<h1>PRIVILEGES</h1>
<hr>

<table id="privileges-table" class="ui celled table nowrap table-hover table-striped display" style="width:100%">
    <thead>
    <tr>
        <th>No.</th>
        <th>Privilege</th>
        <th>Module</th>
        <th>No. of Roles</th>
        <th>Action</th>
    </tr>
    </thead>
    <tfoot>
    <tr>
        <th>No.</th>
        <th>Privilege</th>
        <th>Module</th>
        <th>No. of Roles</th>
        <th>Action</th>
    </tr>
    </tfoot>
</table>

@section Scripts {
    <script src="~/js/security/privilege/get.all.privileges.dt.js"></script>
    <script src="~/js/security/privilege/delete.privilege.js"></script>
    <script src="~/js/security/privilege/count.privilege.roles.js"></script>

}